from datetime import datetime
from typing import Any, Dict, List, Optional

from langchain_core.messages import BaseMessage


REPORT_TEMPLATE = """# {title}

**Generated:** {timestamp}
**Query:** {query}

---

## Executive Summary

{executive_summary}

---

## Market Analysis

{market_analysis}

---

## Transaction & Volume Metrics

{transaction_metrics}

---

## Risk Assessment

{risk_section}

---

## Statistical Insights

{statistical_insights}

---

## Key Findings & Recommendations

{recommendations}

---

## Data Sources

{citations}

---
*Generated by LangGraph ReAct Analyst Agent.*
"""


def synthesize_report(
    query: str,
    data_context: Dict[str, Any],
    messages: List[BaseMessage],
    citations: List[str],
) -> str:
    sections = _extract_sections(data_context)
    return REPORT_TEMPLATE.format(
        title=_infer_title(query),
        timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        query=query,
        **sections,
        citations=_format_citations(citations, data_context),
    )


def _infer_title(query: str) -> str:
    q = query.lower()
    if "ethereum" in q or " eth" in q:   return "Ethereum Market & On-Chain Analysis Report"
    if "bitcoin" in q or " btc" in q:    return "Bitcoin Market Analysis Report"
    if "risk" in q:                       return "Portfolio Risk Assessment Report"
    if "volume" in q or "transaction" in q: return "Transaction Volume & Market Activity Report"
    return "Comprehensive Financial Analyst Report"


def _extract_sections(ctx: Dict[str, Any]) -> Dict[str, str]:
    mkt  = ctx.get("get_market_data", {})
    txn  = ctx.get("query_transaction_analytics", {})
    risk = ctx.get("assess_risk_metrics", {})
    stat = ctx.get("run_statistical_analysis", {})

    # market analysis
    if mkt:
        asset = mkt.get("asset", "Unknown")
        change = mkt.get("price_change_pct", 0)
        direction = "gained" if change >= 0 else "declined"
        market_analysis = (
            f"**{asset}** has {direction} **{abs(change):.1f}%** over the period, "
            f"current price **${mkt.get('current_price_usd', 0):,.2f}**.\n\n"
            f"- Annualized volatility: **{mkt.get('volatility_annualized', 0)*100:.1f}%**\n"
            f"- Sharpe ratio: **{mkt.get('sharpe_ratio', 0):.2f}**\n"
            f"- Max drawdown: **{mkt.get('max_drawdown_pct', 0):.1f}%**\n"
            f"- Avg daily volume: **${mkt.get('avg_daily_volume_usd', 0):,.0f}**"
        )
    else:
        market_analysis = "_Market data not retrieved for this query._"

    # transaction metrics
    if txn:
        transaction_metrics = (
            f"**Total Volume:** ${txn.get('total_volume_usd', 0):,.2f} over {txn.get('period_days', 0)} days\n\n"
            f"- Total transactions: **{txn.get('total_transactions', 0):,}**\n"
            f"- Avg daily active users: **{txn.get('avg_daily_active_users', 0):,}**\n"
            f"- Total fee revenue: **${txn.get('total_fee_revenue_usd', 0):,.2f}**\n"
            f"- WoW volume growth: **{txn.get('wow_volume_growth_pct', 0):+.1f}%**"
        )
    else:
        transaction_metrics = "_Transaction analytics not retrieved for this query._"

    # risk
    if risk:
        vol = risk.get("annualized_volatility_pct", 0)
        level = "HIGH" if vol > 80 else "MEDIUM" if vol > 40 else "LOW"
        risk_section = (
            f"**Risk Level: {level}**\n\n"
            f"- VaR (95%, daily): **{risk.get('var_95_daily', 0):.2f}%** — {risk.get('var_95_pct_interpretation', '')}\n"
            f"- CVaR (tail): **{risk.get('cvar_95_daily', 0):.2f}%**\n"
            f"- Beta vs market: **{risk.get('beta_vs_market', 0):.2f}**\n"
            f"- Annualized volatility: **{vol:.1f}%**"
        )
    else:
        risk_section = "_Risk metrics not retrieved for this query._"

    # stats
    if stat:
        statistical_insights = (
            f"n={stat.get('n', 0)} observations — "
            f"mean **{stat.get('mean', 0):.4f}** | median **{stat.get('median', 0):.4f}** | "
            f"std **{stat.get('std', 0):.4f}** | "
            f"range [{stat.get('min', 0):.4f}, {stat.get('max', 0):.4f}]"
        )
        if "trend_direction" in stat:
            statistical_insights += f"\n- Trend: {stat['trend_direction']} (R²={stat.get('r_squared', 0):.3f})"
    else:
        statistical_insights = "_Statistical analysis not performed for this query._"

    # recommendations
    recs = []
    if mkt and mkt.get("price_change_pct", 0) > 10:
        recs.append("Strong recent performance — watch for mean-reversion risk.")
    if risk and risk.get("annualized_volatility_pct", 0) > 80:
        recs.append("High volatility — size positions conservatively.")
    if txn and txn.get("wow_volume_growth_pct", 0) > 20:
        recs.append("Volume growth +20% WoW — monitor for sustained DAU as confirmation signal.")
    if not recs:
        recs = [
            "Continue monitoring on the cadence defined in this report.",
            "Set automated alerts for VaR breaches and volume anomalies.",
        ]
    recommendations = "\n".join(f"- {r}" for r in recs)

    n_sources = len(ctx)
    executive_summary = (
        f"This report draws from **{n_sources} data source{'s' if n_sources != 1 else ''}**. "
        f"Key findings span market performance, on-chain activity, and risk metrics."
    )

    return {
        "executive_summary": executive_summary,
        "market_analysis": market_analysis,
        "transaction_metrics": transaction_metrics,
        "risk_section": risk_section,
        "statistical_insights": statistical_insights,
        "recommendations": recommendations,
    }


def _format_citations(citations: List[str], ctx: Dict[str, Any]) -> str:
    lines = [f"- **Tools called:** {', '.join(ctx.keys()) or 'none'}"]
    lines += [f"- {c}" for c in citations[:5]]
    return "\n".join(lines)
